[tool.pyright]
reportMissingImports = "warning"
reportMissingTypeStubs = "warning"
reportGeneralTypeIssues = "warning"
reportOptionalSubscript = "warning"
reportOptionalMemberAccess = "warning"
reportOptionalIterable = "warning"
reportUnknownVariableType = "none"
reportUninitializedInstanceVariable = "warning"
reportArgumentType = "warning"
reportCallIssue = "warning"
reportAssignmentType = "warning"